project:
  type: book

book:
  title: "A Crash Course in R for Social Scientists"
  author: "Aditya Ranganath"
  repo-url: https://github.com/aranganath24/IBS_CRDDS_R 
  repo-actions: [source, edit, issue] 
  date: "9/29/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - session1.qmd 
    - session2.qmd
    - session3.qmd
    - session4.qmd
    - session5.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 4
    number-depth: 4
    include-after-body: footer.html
    theme:
      - cosmo

editor: visual

